# SPDX-FileCopyrightText: 2022 Thomas Kramer
#
# SPDX-License-Identifier: CC0-1.0

pipeline:
    build:
        image: rust
        commands:
            - git clone https://codeberg.org/libreda/splay ../splay
            - cargo check
            - cargo test
    reuse:
        image: fsfe/reuse:latest
        commands:
            - reuse lint
